### ISSUE TITLE
Create state changing endpoint

### ISSUE THREAD

**Issue by altenstedt** [Omegapoint/defence-in-depth-java#4]
We want to show patterns from secure by design concerning state changing functions. A suggestion is to add a `AddProductDescription` or similar that shows how changing state would work.  It is also interesting to show how to deal with input data validation for such a free form value as "description".

As an option, we would like to show how to deal with more complex domain logic.  Perhaps an order concept, or some state changing function that affects other parts of the object or domain.  Or a state that changes.

**Comment by erica-edholm** [comment]
Solved by #9 and #11
